<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<html>
<head>
	<?php echo Coffe::getHead()->renderHead() ?>
</head>
<body>
<table>
	<tr>
		<td style="vertical-align: top;"><iframe style="overflow: hidden;" scrolling="no"  frameborder="0" marginheight="0" marginwidth="0" src="<?php echo $this->url($this->module_id,array('action' => 'tree')) ?>" name="nav_frame" id="nav_frame"></iframe></td>
		<td style="vertical-align: top;"><iframe style="overflow: hidden;" scrolling="no"  frameborder="0" marginheight="0" marginwidth="0" src="<?php echo $this->url($this->module_id,array('action' => 'page')) ?>" name="list_frame" id="list_frame"></iframe></td>
</table>
</body>
</html>